// Command gen-traceability re-emits docs/traceability.md and the
// <!-- TRACEABILITY:START --> ... END block in README.md from the
// canonical manifest.go. Run via `make gen`.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/bsv-blockchain/node-validation/internal/matrix"
)

const (
	startMarker = "<!-- TRACEABILITY:START -->"
	endMarker   = "<!-- TRACEABILITY:END -->"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	m := matrix.Load()
	body := renderMatrix(m)

	// Write docs/traceability.md.
	full := "<!-- generated by cmd/gen-traceability — do not edit by hand -->\n\n" +
		"# Traceability matrix\n\n" + body
	if err := os.WriteFile("docs/traceability.md", []byte(full), 0o644); err != nil {
		return fmt.Errorf("writing docs/traceability.md: %w", err)
	}

	// Update README.md between markers.
	readme, err := os.ReadFile("README.md")
	if err != nil {
		return fmt.Errorf("reading README.md: %w", err)
	}
	updated, err := replaceBlock(string(readme), startMarker, endMarker, body)
	if err != nil {
		return err
	}
	if updated != string(readme) {
		if err := os.WriteFile("README.md", []byte(updated), 0o644); err != nil {
			return fmt.Errorf("writing README.md: %w", err)
		}
	}
	return nil
}

func renderMatrix(m matrix.Manifest) string {
	var b strings.Builder
	b.WriteString("## Functional Requirements\n\n")
	b.WriteString("| ID | Title | Coverage | Covered by | Notes |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindFR) {
		fmt.Fprintf(&b, "| %s | %s | `%s` | %s | %s |\n",
			e.ID, escapeMD(e.Title), e.CoverageStatus, strings.Join(e.CoveredBy, ", "), escapeMD(e.Notes))
	}

	b.WriteString("\n## Non-Functional Requirements\n\n")
	b.WriteString("| ID | Title | Coverage | Covered by | Notes |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindNFR) {
		fmt.Fprintf(&b, "| %s | %s | `%s` | %s | %s |\n",
			e.ID, escapeMD(e.Title), e.CoverageStatus, strings.Join(e.CoveredBy, ", "), escapeMD(e.PartialNote+" "+e.Notes))
	}

	b.WriteString("\n## Test Environment\n\n")
	b.WriteString("| ID | Title | Notes |\n|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindTE) {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", e.ID, escapeMD(e.Title), escapeMD(e.Notes))
	}

	b.WriteString("\n## Source-plan test cases\n\n")
	b.WriteString("| ID | Title | Severity | Status | Notes |\n|---|---|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindTC) {
		notes := e.Notes
		if e.ExclusionReason != "" {
			notes = e.ExclusionReason
		}
		fmt.Fprintf(&b, "| %s | %s | %s | `%s` | %s |\n",
			e.ID, escapeMD(e.Title), e.Severity, e.TestCaseStatus, escapeMD(notes))
	}

	b.WriteString("\n## New test cases\n\n")
	b.WriteString("| ID | Title | Severity | Satisfies |\n|---|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindNEW) {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			e.ID, escapeMD(e.Title), e.Severity, strings.Join(e.SatisfiesReqs, ", "))
	}

	b.WriteString("\n## Risks\n\n")
	b.WriteString("| ID | Description | Mitigating tests | Notes |\n|---|---|---|---|\n")
	for _, e := range m.ByKind(matrix.KindR) {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			e.ID, escapeMD(e.Title), strings.Join(e.CoveredBy, ", "), escapeMD(e.Notes))
	}
	return b.String()
}

func escapeMD(s string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), "|", `\|`)
}

func replaceBlock(src, start, end, body string) (string, error) {
	si := strings.Index(src, start)
	ei := strings.Index(src, end)
	if si < 0 || ei < 0 || ei < si {
		return "", fmt.Errorf("README markers not found or out of order")
	}
	return src[:si+len(start)] + "\n\n" + body + "\n" + src[ei:], nil
}
