# compose/aerospike/aerospike.conf
service {
    user root
    group root
    paxos-single-replica-limit 1
    pidfile /var/run/aerospike/asd.pid
    proto-fd-max 15000
}

logging {
    file /var/log/aerospike/aerospike.log {
        context any info
    }
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3000
    }
    heartbeat {
        mode mesh
        port 3002
        interval 150
        timeout 10
    }
    fabric { port 3001 }
    info { port 3003 }
}

namespace teranode1 {
    replication-factor 1
    memory-size 512M
    storage-engine memory
    nsup-period 60
    default-ttl 0
}

namespace teranode2 {
    replication-factor 1
    memory-size 512M
    storage-engine memory
    nsup-period 60
    default-ttl 0
}

namespace teranode3 {
    replication-factor 1
    memory-size 512M
    storage-engine memory
    nsup-period 60
    default-ttl 0
}
